# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Blog title')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Blog tag')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish date')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'ordering': ['-pub_date'],
            },
        ),
    ]
